# Generated by Django 3.2 on 2023-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
